In [1]:
import numpy as np
import sys
import ipdb

sys.path.append("../")

sys.path.append("../utils/")
from utils_functions import *

from dd_game import *
from two_stage_player import *

# Configurations

In [2]:
#TODO: There are many configuration parameters here. It is important to understand the effect of all.
d = 2
coeff_var = 1

Sigma_x_p1 = np.eye(d)
Sigma_x_p2 = np.eye(d)

sigma_y_p1 = 1
sigma_y_p2 = 1

beta_p1 = np.random.normal(size = d)
beta_p2 = np.random.normal(size = d)

"""
mu_p1 = np.random.normal(scale = coeff_var, size = d)
mu_p2 = np.random.normal(scale = coeff_var, size = d)
gamma_p1 = np.random.normal(scale = coeff_var, size = d)
gamma_p2 = np.random.normal(scale = coeff_var, size = d)
"""

#Fixing mu and gamma for testing purposes
mu_p1 = np.array([2.1, -1.8])
gamma_p1 = np.array([1.2, 0.9])
mu_p2 = np.array([-2.8, 2.2])
gamma_p2 = np.array([0.7, -0.3])

In [3]:
p1_data_params = (Sigma_x_p1, sigma_y_p1, beta_p1, mu_p1, gamma_p1)
p1_data_generating_func = sample_from_location_family

p2_data_params = (Sigma_x_p2, sigma_y_p2, beta_p2, mu_p2, gamma_p2)
p2_data_generating_func = sample_from_location_family

num_rounds_lst = [10, 100, 1000, 10000, 40000]
num_alternate_rounds = 1000
num_test = 10000

# Run Game

In [4]:
#Initialize game with configurations specified above


for num_rounds in num_rounds_lst:
    player_two = TwoStagePlayer()
    player_one = TwoStagePlayer()
    game = DecisionDependentGame(player_one, player_two, p1_data_params, p2_data_params, 
                             p1_data_generating_func, p2_data_generating_func, 
                             num_rounds, num_alternate_rounds, num_test)
    print(game.solve_nash())
    game.run_train()
    
    print(game.evaluate_test_perf_risk_p1())
    print(game.evaluate_test_perf_risk_p2())
    
    game.run_post_train_alternating()
    
    print(game.evaluate_test_perf_risk_p1())
    print(game.evaluate_test_perf_risk_p2())
    
    #Change this flag if one wants to change print settings
    if False:
        print("---------------------")
        print("Player 1")
        print(mu_p1, gamma_p1)
        print(player_one.mu_hat, player_one.gamma_hat)

        print("Player 2")
        print(mu_p2, gamma_p2)
        print(player_two.mu_hat, player_two.gamma_hat)

(array([-0.08937719, -0.54499883]), array([-0.00955091, -1.09602379]))
Stage 1 finished. Performing estimation now
Stage 1 finished. Performing estimation now
Stage 2 finished. Finding qs now.
Stage 2 finished. Finding qs now.
10.126125228609986
8.910342381815143
100.90224197318942
182.78642347021596
(array([-0.08937719, -0.54499883]), array([-0.00955091, -1.09602379]))
Stage 1 finished. Performing estimation now
Stage 1 finished. Performing estimation now
Stage 2 finished. Finding qs now.
Stage 2 finished. Finding qs now.
4.850133442188525
252.08962974706782
2.367476584496769
3.323535466533957
(array([-0.08937719, -0.54499883]), array([-0.00955091, -1.09602379]))
Stage 1 finished. Performing estimation now
Stage 1 finished. Performing estimation now
Stage 2 finished. Finding qs now.
Stage 2 finished. Finding qs now.
6.28638723066219
7.544273924833674
2.476769724980002
3.2007079483310226
(array([-0.08937719, -0.54499883]), array([-0.00955091, -1.09602379]))
Stage 1 finished. Performing

In [5]:
if False:
    print(mu_p1, gamma_p1)
    print(player_one.mu_hat.round(2), player_one.gamma_hat.round(2))

    print(mu_p2, gamma_p2)
    print(player_two.mu_hat.round(2), player_two.gamma_hat.round(2))

    print(game.solve_nash())
    
    print(game.solve_social_opt())
    
    print(game.evaluate_test_perf_risk_p1().round(3))
    print(game.evaluate_test_perf_risk_p2().round(3))

## Checking stage 1

In [6]:
print(player_one.mu_hat, player_one.gamma_hat)
print(player_two.mu_hat, player_two.gamma_hat)

[ 2.11062538 -1.8139493 ] [1.20467457 0.88274074]
[-2.77932406  2.18267021] [ 0.68695142 -0.28524824]


In [7]:
print(mu_p1, gamma_p1)
print(mu_p2, gamma_p2)

[ 2.1 -1.8] [1.2 0.9]
[-2.8  2.2] [ 0.7 -0.3]


## Evaluate the performative risks before and after Stage 3

In [8]:
PR_1 = game.evaluate_test_perf_risk_p1()
PR_2 = game.evaluate_test_perf_risk_p2()
print(f'Player 1 PR = {PR_1.round(3)}\tPlayer 2 PR = {PR_2.round(3)}')

Player 1 PR = 2.556	Player 2 PR = 3.205


In [9]:
print(player_one.theta_history[-1])
print(player_two.theta_history[-1])

[-0.07962925 -0.56002032]
[-0.59377613 -0.62589447]


In [10]:
game.theta_p1, game.theta_p2 = game.solve_nash()
PO_1 = game.evaluate_test_perf_risk_p1()
PO_2 = game.evaluate_test_perf_risk_p2()
print(f'Player 1 PO = {PO_1.round(3)}\tPlayer 2 PO = {PO_2.round(3)}')

Player 1 PO = 2.425	Player 2 PO = 11.15


In [11]:
game.theta_p1, game.theta_p2 = game.solve_social_opt()
SO_1 = game.evaluate_test_perf_risk_p1()
SO_2 = game.evaluate_test_perf_risk_p2()
print(f'Player 1 SO = {SO_1.round(3)}\tPlayer 2 SO = {SO_2.round(3)}')

Player 1 SO = 2.471	Player 2 SO = 4.244
